  
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';